Unused local variable and fixed wrong type of the parameter
FriendsOfSymfony1/doctrine1 pull request #118
Opened 2024-02-05 00:41 UTC by miamibc

Constant problem of projects with Symfony1 - wrong type `string` in phpdoc block for function Collection::fromArray()  must be `array`

2024-02-05 06:46 UTC, connorhu approved these changes
I prefer the two different modifications in separate commits, but the fix is fine! Thanks for the PR.

2024-02-08 19:25 UTC, thePanz requested changes
LGTM, please:
1. Split the code change in two different commits
2. Rebase on latest master branch

Then it can be merged

2024-02-09 09:34 UTC, miamibc commented
You made me a quest from very very very dumb fix. 
Is it **really** necessary to split **this** into two commits?

2024-02-09 09:52 UTC, thePanz commented
> You made me a quest from very very very dumb fix. Is it **really** necessary to split **this** into two commits?

I feel like a clean way to proceed, I can prepare those two changes myself and set you as author.
Let me know

2024-02-09 10:05 UTC, thePanz approved these changes

2024-02-09 10:05 UTC, merged